#!/usr/bin/env bash
# To-do: check for proper failures.

set -u

cargo llvm-cov clean --workspace
./do coverage --no-report --quiet
echo {} | cargo llvm-cov run --no-report --quiet
echo f | cargo llvm-cov run --no-report --quiet
printf '\xFF\xFE' | cargo llvm-cov run --no-report --quiet
cargo llvm-cov run --no-report --quiet -- --help
cargo llvm-cov report --html
