name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/determinate-nix-action@v3
      - uses: cachix/cachix-action@v16
        with:
          name: json2dir
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build --print-build-logs
