name: 100% region coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        # FIXME(2025): cargo-llvm-cov is broken on macos-latest
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/determinate-nix-action@v3
      - run: nix build --print-build-logs .#check-coverage
